from enum import Enum


class EstadoConversacion(Enum):
    BIENVENIDA = "BIENVENIDA"
    ESPERANDO_LEGAJO = "ESPERANDO_LEGAJO"
    ESPERANDO_FECHA_INICIO = "ESPERANDO_FECHA_INICIO"
    ESPERANDO_FECHA_FIN = "ESPERANDO_FECHA_FIN"
    ESPERANDO_APROBACION_SUPERVISOR = "ESPERANDO_APROBACION_SUPERVISOR"
    FINALIZADO = "FINALIZADO"